clear
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Ty Freeman\Documents\Classes\Grad_Paper\tkf1604_grad_ppr\STM_FFT\Tests\Data_Files\DT_Export.csv
%
% Auto-generated by MATLAB on 20-Apr-2023 23:46:57

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [29, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Channel1V"];
opts.SelectedVariableNames = "Channel1V";
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
DTExport1 = readtable("C:\Users\Ty Freeman\Documents\Classes\Grad_Paper\tkf1604_grad_ppr\STM_FFT\Tests\Data_Files\DT_Export.csv", opts);

%% Convert to output type
DTExport1 = table2array(DTExport1);

%% Clear temporary variables
clear opts

fs = 800*1e3;
N = length(DTExport1);
dt = 1/fs;
t = 0:dt:(N-1)*dt;
f = linspace(0,fs/2,N/2+1);
h = hann(N);
x = DTExport1; % Apply Hanning Window

X = abs(fft(x,N))/N; % Normalized Magnitude of fft output
X = X(1:N/2+1); % Single-sided conversion
X(2:end-1) = sqrt(2).*X(2:end-1); % Amplitude Vrms for non-DC components
X = X*2; % Window Correction factor

%% Results plotting
figure
plot(t,x);
title("Signal in Time Domain")
xlim([0 0.0102])
xlabel("Time (s)")
ylabel("Amplitude (V)")

figure
plot(f,X);
title("MATLAB FFT Results")
xlim([0 2000])
xlabel("Frequency (Hz)")
ylabel("Amplitude (Vrms)")